version: '3.8'

services:
  web:
    build: .
    entrypoint: ["/code/entrypoint.sh"]
    command: gunicorn CesiZen.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
      - static_volume:/code/CesiZen/staticfiles
      - media_volume:/code/media
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=CesiZen.settings
    depends_on:
      - db
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  media_volume:
  postgres_data:
