# Generated by Django 5.1.5 on 2025-01-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_age_user_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
    ]
