# Generated by Django 5.1.5 on 2025-01-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
