# Generated by Django 5.1.5 on 2025-01-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_userinline_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default/user_logo.png', upload_to='profile_pictures/'),
        ),
    ]
