# Generated by Django 5.1.5 on 2025-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_activity_favoriteactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien vers une vidéo (YouTube, Vimeo...)', null=True),
        ),
    ]
