# Generated by Django 5.1.5 on 2025-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_information_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
